[package]
name = "santa_paravia"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.1"
text_io = "0.1.12"
array-init = "2.1.0"
clearscreen = "3.0.0"
